### ISSUE TITLE
测试BLSS时，发现HLS分片不支持h265/hevc

### ISSUE THREAD

**Issue by hougang2013** [gnolizuh/BLSS#118]

**Comment by gnolizuh** [comment]
flv tag 里的 hevc codec_id 设置的对吗?

**Comment by hougang2013** [comment]
我按照金山云提供的rtmp/flv协议扩展方式，对ffmpeg进行了扩展，其codec_id=12。扩展方法：https://github.com/ksvc/FFmpeg

**Comment by hougang2013** [comment]
![image](https://user-images.githubusercontent.com/8747891/51588456-3418d280-1f1f-11e9-8f7c-35c40c2d6f18.png)

**Comment by gnolizuh** [comment]
HLS 支持 hevc 的代码暂未合入。

**Comment by hougang2013** [comment]
期待合入！   我现在都是直接用ffmpeg进行hls切片的，性能不行！  执行的exec_push   ffmpeg

**Comment by wellttllew** [comment]
@hougang2013

**Comment by wellttllew** [comment]
@hougang2013  我发现可以用 `ngx-ts-module`  ，不过目前官方的没有切在 `gop` 边界上：  

- `ksffmpeg -i rtmp://xxxx/live/xxx -c copy -f mpegts http://nginx-with-ts-module/publish/hls/xxxx `  
    - `ksffmpeg` 指金山的 `ffmpeg` 哈。   
- 我发现官方没有判断是否为`HEVC`，我在我的 patch 里面添加了支持  
- 另外官方使用的 `Meta` 里面的 `Random Access Indicator` 来判断是否为 `IDR` 帧，有的 `ts` 打包器（额，比如我们公司的）里面不会有 `meta`，所以 `IDR `帧没法准确判断 （这个我没有做，感觉要去通过 ES 数据来判断）    

Check [This](https://github.com/arut/nginx-ts-module/issues/42)
