### ISSUE TITLE
按照你的那个rtmp配置文件说明不能使用

### ISSUE THREAD

**Issue by jingshaoqi** [gnolizuh/BLSS#61]
能再完善一下你的那个rtmp配置文件说明不?
其中的那个service cctv不知道是做什么用的?

我采用下面的方式发布流不成功:
ffmpeg -re -i output.flv -codec copy -f flv rtmp://127.0.0.1:1935/cctv/news/a.pub.rtmp.cctv

**Comment by gnolizuh** [comment]
service是vhost的概念，也就是租户，一个租户可以有多个域名，不会在发布的URL中体现。但会根据hostname来匹配。而hostname是用来过滤推拉流URL的，用法是```hostname [pub|sub] [rtmp|http_flv] domain1 domain2;```

首先你需要绑一下host，127.0.0.1 a.pub.rtmp.cctv，然后再发布：
ffmpeg -re -i output.flv -codec copy -f flv rtmp://a.pub.rtmp.cctv:1935/news/streamname

**Comment by gnolizuh** [comment]
有时间我会完善一下配置说明的。

**Comment by superxrb** [comment]
建议增加一下直接使用IP地址推流和拉流，而不是只能使用域名！

**Comment by gnolizuh** [comment]
嗯，这是个需求，我来加。

**Comment by superxrb** [comment]
你什么时候有空将支持直接使用ip地址推流和拉流的功能增加进去呢，我们的项目服务器在摄像机上面，需要直接使用IP地址进行访问，谢谢！

**Comment by gnolizuh** [comment]
我今天来支持一下

**Comment by gnolizuh** [comment]
done。

使用方式详见中文README。

**Comment by superxrb** [comment]
好的，谢谢！
