### ISSUE TITLE
add_header属性能使用吗

### ISSUE THREAD

**Issue by wxzcyy** [gnolizuh/BLSS#74]

**Comment by gnolizuh** [comment]
你是指针对http flv的add_header配置吧。

**Comment by wxzcyy** [comment]
是的，我想给响应头添加 Access-Control-Allow-Origin: *

**Comment by gnolizuh** [comment]
了解，FLASH跨域问题，这个目前还不支持，我想想办法

**Comment by wxzcyy** [comment]
谢谢您的解答

**Comment by superxrb** [comment]
其实有个山寨办法，就是直接将支持跨域访问的头直接加到ngx_http_flv_header这个字符串常量上面。

**Comment by gnolizuh** [comment]
嗯，是可以，但是这样实现不完美。

**Comment by gnolizuh** [comment]
add_header 功能正在支持

**Comment by gnolizuh** [comment]
done
