### ISSUE TITLE
http-flv文件头问题

### ISSUE THREAD

**Issue by wxzcyy** [gnolizuh/BLSS#77]
当直播源没有视频或者音频时，拉下来的`http-flv`直播流`has audio`和`has vedio`都是1，即使在推流时使用`-an`禁掉视频或者音频还是这样。好像是转码时没有判断吧？

**Comment by gnolizuh** [comment]
我理解如果是直播的话，只能说当时有没有音视频，如果给了no audio/video的话，后面是不是没有机会再更新了。

**Comment by gnolizuh** [comment]
你有遇到过这类问题吗? 具体播放是怎么个逻辑能说一下吗?

**Comment by wxzcyy** [comment]
我通过`ffmpeg -i rtsp://** -vcodec libx264 -acodec aac -f flv rtmp://**`将摄像机的流推到`BLSS`上，然后通过`flv.js`在`<vedio>`中播放拉下来的`http-flv`数据流。因为`flv header`中`has audio=1`，所以浏览器默认要获取到`Audio Tag`，但是并没有`Audio Tag`，所以浏览器一直在等待，播放失败。

**Comment by wxzcyy** [comment]
忘了说了，我的网络摄像头是没有音频的

**Comment by gnolizuh** [comment]
你可以更新代码再试试

**Comment by wxzcyy** [comment]
可以了

**Comment by wxzcyy** [comment]
但是有时候经常会出现推流一段时间后自动断开，提示WriteN, RTMP send error 104 (136 bytes)

**Comment by gnolizuh** [comment]
有coredump吗，或者贴一下日志。

**Comment by wxzcyy** [comment]
2017/07/21 20:23:58 [alert] 1664#0: worker process 1666 exited on signal 11 (core dumped)

**Comment by gnolizuh** [comment]
你会看堆栈么，或者说一下复现步骤，谢谢。

**Comment by wxzcyy** [comment]
很奇怪，我重启了几次，这个错误没有再出现过了

**Comment by gnolizuh** [comment]
有core文件，或者core dumped上面几行日志有么
