### ISSUE TITLE
跨域访问要怎么配置呢？

### ISSUE THREAD

**Issue by superxrb** [gnolizuh/BLSS#88]
使用flvjs播放推流，发现无法跨域，用vlc可以正常播放。

**Comment by gnolizuh** [comment]
你的问题应该和这个issue一样，https://github.com/gnolizuh/BLSS/issues/74

**Comment by superxrb** [comment]
嗯，好。就是老大让我询问一下，这个issue可以关闭了。

**Comment by gnolizuh** [comment]
这个特性还不是很好支持，但你们可以加个中间nginx，用这个nginx来加会比较灵活。
